import type { Metadata } from "next";
import type React from "react";
import { Suspense } from "react";
import RefineContext from "./_refine_context";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
			<html className="gs" lang="en">
				<body>
					<Suspense>
						<RefineContext>
							{children}
						</RefineContext>
					</Suspense>
				</body>
			</html>
		);
}
